// Splash lines shown in the prompt bar while the agent is working.
const SPLASH: readonly string[] = [
  // Core
  "Rip and tear.",
  "Until it is done.",
  "Crush. Kill. Compile.",
  "Rip. Tear. Refactor.",
  "The Slayer has entered the terminal.",
  "The Only Thing They Fear Is Your Code.",
  "No rest for the living.",
  "Your task. Your weapons. Your fight.",
  "Your code. Your weapons. Your fight.",
  "Until the code is done.",
  "The Slayer has awakened.",
  "The Slayer is ready.",
  "The Slayer does not negotiate.",
  "The Slayer does not stop.",
  "The Slayer does not surrender.",
  "The Slayer knows no fear.",
  "The Slayer has entered the facility.",
  "The Slayer has entered the codebase.",
  "The Slayer is approaching the repository.",
  // Code
  "Rip and tear through the codebase.",
  "Rip. Tear. Debug. Repeat.",
  "Terminate. Refactor. Repeat.",
  "Kill the bug. Ship the code.",
  "Destroy the demons. Fix the bugs.",
  "No demons. No excuses.",
  "The codebase won't refactor itself.",
  "The demons broke production.",
  "A demon has entered the stack.",
  "A demon has entered the repository.",
  "A demon has entered the dependency tree.",
  "The codebase has been corrupted.",
  "Compiling...",
  "Refactoring...",
  "Debugging...",
  "Purging corrupted code...",
  "Exterminating legacy code...",
  "Terminating deprecated functions...",
  "No mercy for technical debt.",
  "Technical debt has been marked for termination.",
  "The bugs will be destroyed.",
  "The bugs will not survive.",
  "The stack trace leads deeper.",
  "The call stack goes deeper.",
  "The recursion never ends.",
  "The demons are in the dependency tree.",
  "The dependency tree is compromised.",
  "The repository is under attack.",
  "The codebase is under siege.",
  "The UAC has deployed a coding agent.",
  // UAC terminal
  "UAC SYSTEM ONLINE.",
  "UAC NETWORK CONNECTED.",
  "UAC TERMINAL READY.",
  "UAC DATABASE ACCESSED.",
  "UAC SECURITY OVERRIDE.",
  "UAC WARNING: DEMONIC ACTIVITY DETECTED.",
  "UAC WARNING: CODE INTEGRITY COMPROMISED.",
  "UAC WARNING: PRODUCTION IS ON FIRE.",
  "UAC: ARGENT ENERGY LEVELS CRITICAL.",
  "UAC: ARGENT ENERGY LEVELS NOMINAL.",
  "UAC: SLAYER STATUS CONFIRMED.",
  "UAC: SLAYER DEPLOYED.",
  "UAC: ALL SYSTEMS NOMINAL.",
  "UAC: SOMETHING WENT VERY WRONG.",
  "UAC: AUTHORIZATION ACCEPTED.",
  "UAC: AUTHORIZATION DENIED.",
  "UAC: OVERRIDE ACCEPTED.",
  "UAC: LOCKDOWN INITIATED.",
  // Argent
  "Argent energy levels: CRITICAL.",
  "Argent energy levels: NOMINAL.",
  "Argent energy levels: OVER 9000.",
  "Argent reserves depleted.",
  "Argent reserves restored.",
  "Argent reactor online.",
  "Argent reactor unstable.",
  "Argent reactor approaching critical.",
  "Argent surge detected.",
  "The Argent core is online.",
  "The Argent core is unstable.",
  "Someone left the Argent reactor running.",
  // Weapons
  "Loading BFG 9000...",
  "BFG 9000: READY.",
  "BFG 9000: ARMED.",
  "BFG 9000: TARGET ACQUIRED.",
  "Super Shotgun: LOADED.",
  "Super Shotgun: READY.",
  "Rocket Launcher: READY.",
  "Plasma Rifle: ONLINE.",
  "Chaingun: SPINNING UP.",
  "Chainsaw: READY.",
  "Chainsaw: OUT OF FUEL.",
  "BFG 9000: RESERVED FOR PRODUCTION.",
  "BFG 9000: DEPLOYING TO LEGACY CODE.",
  "Chainsaw: DEPLOYING TO TECHNICAL DEBT.",
  "Super Shotgun: DEPLOYING TO BUGS.",
  // Unhinged
  "Who gave the demons Git access?",
  "The demons have admin privileges.",
  "The UAC forgot to rotate the API key.",
  "The demons have sudo.",
  "The demons have a merge conflict.",
  "The demons force-pushed to main.",
  "The demons deleted production.",
  "The demons skipped code review.",
  "The demons approved their own PR.",
  "The Slayer does not use code review.",
  "The Slayer has no pending PRs.",
  "The Slayer has 0 lint errors.",
  "The Slayer has 0 unresolved comments.",
  "The Slayer has 0 regrets.",
  "The Slayer has root.",
  "The Slayer has sudo.",
  "rm -rf has been authorized.",
  "Production has been declared a combat zone.",
  "The terminal has become a combat arena.",
  "Your dependencies have been possessed.",
  "Your virtual environment is not so virtual anymore.",
  // Short
  "Debug. Destroy. Deploy.",
  "Compile. Destroy. Repeat.",
  "Code integrity compromised.",
  "Production is a combat zone.",
]

// Never repeats the previous line back-to-back.
export function randomSplash(previous?: string): string {
  if (SPLASH.length === 1) return SPLASH[0]!
  let next = SPLASH[Math.floor(Math.random() * SPLASH.length)]!
  while (next === previous) next = SPLASH[Math.floor(Math.random() * SPLASH.length)]!
  return next
}
